baseURL: "https://atacamacontent.netlify.app/"
theme: "up-business"
languageCode: "en-us"

title: "Atacama"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "La plataforma de ropa por suscripcion."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "CABA, Bueno Aires"
    - "Santiago, Chile"

  contact:
    - "atacamacontacto@gmail.com"
    - "+54 9 11 28053716"

  copyright: "© 2022 Atacama All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Que Hacemos"
      url: "/#"
      weight: 2

    - name: "Nuestro Equipo"
      url: "/#"
      weight: 3

    - name: "Precios"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contactanos"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Inicio"
      url: "/#hero"
      weight: 1

    - name: "Que Hacemos"
      url: "/#"
      weight: 2

    - name: "Nuestro Equipo"
      url: "/#"
      weight: 3

    - name: "Precios"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
